CREATE DATABASE INTERMEDIATE_CONCEPT;
USE INTERMEDIATE_CONCEPT;
-- CREATED AND USING DATABASE - " INTERMEDIATE_CONCEPT "


-- MASTER TABLES : CITY AND DEPT --
-- CREATING CITY TABLE (MASTER TABLE):
CREATE TABLE CITY(
CITY_ID INT PRIMARY KEY,
CITY_NAME VARCHAR(20)
);
-- CREATING DEPT TABLE (MASTER TABLE):
CREATE TABLE DEPT(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(20)
);
