CREATE DATABASE INTERMEDIATE_CONCEPT;
USE INTERMEDIATE_CONCEPT;
-- CREATED AND USING DATABASE - " INTERMEDIATE_CONCEPT "


-- MASTER TABLES : CITY AND DEPT --
-- CREATING CITY TABLE (MASTER TABLE):
CREATE TABLE CITY(
CITY_ID INT PRIMARY KEY,
CITY_NAME VARCHAR(20)
);
-- CREATING DEPT TABLE (MASTER TABLE):
CREATE TABLE DEPT(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(20)
);

-- INSERTING DATA TO MASTER TABLES :
-- INSERTING DATA TO CITY TABLE (MASTER)
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES
(1,'CHENNAI'),(2,'BANGALORE'),(3,'HYDERBAD'),(4,'PUNE'),(5,'MUMBAI'),(6,'KOLKATA'),(7,'DELHI');

-- INSERTING DATA TO DEPT TABLE (MASTER)
INSERT INTO DEPT(DEPT_ID , DEPT_NAME) VALUES
(1,'WEB_DESIGNER'),(2,'FRONT-END_DEVELOPER'),(3,'BACK-END_DEVELOPER'),(4,'SQL_DEVELOPER'),(5,'DEVOPS_DEVELOPER'),(6,'FULL-STACK_DEVELOPER');

